---
title: "Analyses for considering the Right to Health in the Universal Periodic Review"
author: "Anshu Uppal"
date: "2025-08-12"
date-modified: last-modified # Dynamic modified date
format:
        html:
                code-fold: true
                toc: true
                toc-location: left  # Place TOC on the left side
                toc-depth: 5        # Include headers up to level 3 (###)
                toc-title: "On this page" # Custom title for the TOC
                smooth-scroll: true # Enable smooth scrolling
                embed-resources: true # Make the html file self contained
                grid: 
                  body-width: 1100px
                  margin-width: 100px
reference-location: margin
citation-location: margin
fig-format: svg
knitr: 
  opts_chunk: 
    dev: svglite
    fig.path: /output/figures/analysis/
---

```{r}
#| message: false

# install.packages("pacman")
pacman::p_load(
  here,
  tidyverse,
  # plotly,
  janitor,
  DT,
  gt,
  sf,
  necountries,
  patchwork,
  Hmisc,
  ggmapinset,
  cowplot,
  magick,
  scatterpie,
  ggnewscale,
  lme4,
  lmerTest,
  lspline,
  optimx,
  effects,
  broom.mixed,
  marginaleffects,
  emmeans,
  modelsummary,
  ggeffects
)

# Load in custom functions
source(here("utils.R"))
source(here("code", "external_data_GBD.R"))

# Read in pre-processed datasets
state_geo <- readRDS(here("output", "state_geo_enhanced.rds"))
sdg_data <- readRDS(here("data", "SDG_data_enhanced.rds")) |> 
  filter(!cycle %in% c("Cycle 4"
                       # , "Cycle 3"
                       )) |> 
  droplevels() |> 
  left_join(state_geo |> sf::st_drop_geometry() |> 
              select(country, region, wbregion, subregion, income, FCS_status), 
            join_by(state_under_review == country))
nearest_neighbors_list <- readRDS(here("output", "nearest_neighbors_list.rds"))

theme_labels <- source(here("code", "theme_labels.R"))$value # not sure why this returns as a list object rather than a simply dataframe

# Loop through API-generated files to read each one and assign it to an object
for (file_name in list.files(path = here("data", "API_data"), 
                             pattern="\\.rds$",
                             full.names = FALSE)) {
  # Create a variable name by removing the ".rds" extension
  object_name <- gsub("\\.rds$", "", file_name)
  
  # Read the .rds file and assign it to the new variable name
  assign(object_name, readRDS(here("data", "API_data", file_name)))
}
```

## UPR summary figures
```{r}
#| fig-height: 9.5
#| fig-width: 8
#| message: false
a_1 <- sdg_data |> 
  select(wbregion, cycle, state_under_review, health_related:maternal_health, response_upr) |> 
  group_by(wbregion, cycle, response_upr) |> 
  summarise(across(c(health_related:maternal_health), ~ sum(.x !="Other"))) |> 
  ungroup() |> 
  filter(response_upr %in% c("Supported", "Noted/Other")) |>
  pivot_longer(cols = health_related:maternal_health, 
               names_to = "theme", 
               values_to = "n"
  )

a_2 <- sdg_data |> 
  select(wbregion, cycle, state_under_review, health_related:maternal_health, response_upr) |> 
  # mutate(across(c(health_related:maternal_health), ~ .x != "Other")) |> 
  group_by(wbregion, cycle, response_upr) |> 
  summarise(across(c(health_related:maternal_health), ~ sum(.x =="Other"))) |> 
  ungroup() |> 
  filter(response_upr %in% c("Supported", "Noted/Other")) |>
  pivot_longer(cols = health_related:maternal_health, 
               names_to = "theme", 
               values_to = "n_other"
  )

a_3 <- sdg_data |> 
  group_by(wbregion, cycle) |> 
  summarise(health_n = sum(health_related !="Other")) |> 
  ungroup()

a <- left_join(a_1,a_2) |> 
  left_join(a_3) |> 
  mutate(cycle = fct_recode(cycle, "1"="Cycle 1", "2"="Cycle 2", "3"="Cycle 3", "4"="Cycle 4")) |> 
  group_by(wbregion, cycle, theme) |> 
  mutate(n_tot = sum(n)+sum(n_other)) |> 
  mutate(n_tot_theme = sum(n)) |> 
  mutate(perc = n/n_tot*100,
         perc_theme = n_tot_theme/n_tot*100,
         theme_perc_health = n_tot_theme/health_n*100) |> 
  group_by(wbregion, cycle, theme) |> 
  mutate(n_sup = paste0("(", sprintf("%1.0f", n/sum(n)*100), "%)"),
         n_sup = case_when(n_tot_theme == 0 ~ "(NA)", .default = n_sup)) |> 
  # mutate(n_sup = case_when(
  #   response_upr == "Noted/Other" ~ "",
  #   response_upr == "Supported" ~ paste0("(", sprintf("%1.0f", n/sum(n)*100), "%)"),
  #   .default = NA
  # )) |> 
  ungroup() |> 
  filter(!theme %in% c(
    "health_related"
    # , "abortion"
    , "TB_malaria", "NTD"
    # , "TB_malaria_NTD"
  )) |> 
  left_join(theme_labels, join_by(theme == variable))


selected_region <- unique(a$wbregion)

for (i in 1:length(selected_region)) {
  a_region <-  a |> 
    filter(wbregion == selected_region[i]) |> 
    arrange(fct_rev(cycle), -n_tot_theme) |> 
    mutate(theme_label = case_when(is.na(theme_label) ~ theme, .default = theme_label),
           theme_label = fct_inorder(theme_label))
  
  max_a <- max(a_region |> pull(perc_theme))
  theme_plot <- a_region |> 
    # mutate(n_tot_theme = case_when(response_upr!="Supported" ~ "", 
    #                                .default = as.character(n_tot_theme))) |> 
    ggplot(aes(x = perc, y = fct_rev(cycle)))+
    geom_col(aes(fill = response_upr))+
    facet_grid(
      rows = vars(theme_label), switch = "y",
      labeller = labeller(theme_label = label_wrap_gen(50))
    )+
    labs(x = "Proportion of all recommendations per UPR cycle (%)", y = NULL,
         fill = "State's response",
         title = paste("Health-related recommendations in each cycle of the UPR\n", selected_region[i]),
         caption = "*Numbers after the bars indicate N (% supported)")+
    # theme_bw()+
    theme_classic()+
    # scale_y_discrete(expand = c(0.1, 0))+
    scale_x_continuous(labels = function(x) paste0(x, "%"), 
                       limits = c(0,max_a+2), 
                       # sec.axis = dup_axis(name = NULL),
                       expand = expansion(mult = c(0, 0.05)) # 0 exactly on axis
    )+
    theme(
      legend.position = "inside",
      legend.position.inside = c(1,0.5),
      legend.justification = c("right", "center"),
      legend.frame = element_rect(color = "black"),
      legend.text = element_text(size = 12),
      legend.title = element_text(size = 15),
      axis.text.y = element_text(size = 10, face = "bold"), 
      axis.text.x = element_text(size = 12),
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
      plot.title.position = "plot",
      strip.placement = "outside",
      strip.text.y.left = element_text(angle = 0, vjust = 1, size = 11),
      strip.background = element_rect(fill = NA, linewidth = 1, color = "black", linetype = 1),
      panel.grid = element_blank()
    )+
    geom_text(
      data = a_region |> filter(response_upr == "Supported"),
      aes(label = paste0(n_tot_theme, " ", n_sup), x = perc_theme),
      hjust = -0.15, size = 3.5 , vjust=0.25
    )
  print(theme_plot)
}
```

## UPR summary tables: maternal health and family planning
```{r}
sdg_data |> 
  arrange(region, wbregion, subregion) |> 
  mutate(subregion = fct_inorder(subregion)) |> 
  filter(maternal_health != "Other") |> 
  filter(!is.na(response_upr)) |> 
  group_by(subregion) |> 
  count(response_upr) |> 
  ggplot(aes(y = subregion, x = n, fill = response_upr))+
  geom_col()+
  labs(x = "Number of recommendations", y=NULL, title = "Recommendations related to maternal health, by region")+
  theme_bw()
```

```{r}
#| fig-width: 13
#| fig-height: 5
p1<-a |> 
  filter(!theme %in% c("health_related")) |> 
  filter(theme %in% c(
    # "GBV"
    "maternal_health",
    "abortion",
    "contraception",
    "SRHR"
  )) |> 
  # group_by(cycle, theme) |> 
  ggplot(aes(x = cycle, y = perc, fill = response_upr))+
  # scale_fill_manual(values = c("Noted/Other" = "#FFC300", "Supported" = "#5669f1"))+
  labs(x = "UPR cycle", y = "% of total recommendations", 
       fill = "State's response",
       title = "Percent of total UPR recommendations by theme\nSupported % in brackets")+
  geom_col()+
  # geom_text(aes(label = n_sup), size = 5, hjust = 0.5, color = "grey20", 
  #           position = position_stack(vjust = 0.5))+
  # geom_text(aes(label = n_sup, y = if_else(perc<1,1.6,perc/2)), size = 5, color = "white")+
  # geom_text(aes(label = sprintf("%1.0f", n_tot_theme), y = sum(perc), vjust =-0.2), size = 5)+
  facet_wrap(.~theme,
             nrow = 1,
             labeller = as_labeller(c("abortion" = "Abortion",
                                      "GBV" = "Gender-based violence",
                                      "contraception" = "Contraception/Family planning",
                                      "maternal_health" = "Maternal health",
                                      "SRHR" = "SRHR")))+
  theme_bw()+
  theme(panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.title.x = element_text(size=16),
        axis.title.y = element_text(size = 16),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 16),
        legend.position = "inside",
        legend.position.inside = c(0,1),
        legend.justification = c("left", "top"),
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 14),
        legend.background = element_blank())+
  scale_y_continuous(sec.axis = dup_axis(name = NULL)
                     # , limits = c(0,13)
  );p1
ggsave("recommendations_by_theme.png", p1, width = 8, height = 4.5)
# ggsave("recommendations_by_theme_gbv.png", p1, width = 9, height = 4)

```

## MMR
```{r}
mmr_05_23 <- MMR |> 
  filter(!is.na(COUNTRY)) |> 
  select(ParentLocation, COUNTRY, country_name, YEAR, NumericValue) |> 
  mutate(NumericValue = round(NumericValue)) |> 
  arrange(COUNTRY, YEAR) |> 
  # filter(YEAR %in% c(2005, 2016, 2023)) |> 
  pivot_wider(names_from = YEAR, values_from = NumericValue, names_prefix = "mmr_")

chosen_year <- "2005";chosen_year_sym <- paste0("mmr_", chosen_year) |> sym()
p1<-mmr_05_23 |> 
  filter(country_name!="Cook Islands") |> 
  # filter(mmr_2023>=mmr_2016) |> 
  # mutate(improved = factor(case_when(mmr_2023<mmr_2016 ~ "Improved", .default = "Not improved"), 
  #                          levels = c("Improved", "Not improved"))) |> 
  ggplot(aes(x=!!chosen_year_sym, y = mmr_2023, color = ParentLocation, text = country_name))+
  geom_abline(intercept = 0, slope = 1, linetype = 2)+
  labs(x=paste0("MMR in ", chosen_year," (axis on log-scale)"), y="MMR in 2023 (axis on log-scale)")+
  geom_point(
    # aes(alpha = increase)
  )+
  theme_bw()+
  # scale_alpha_manual(values = c(1,0.1))+
  # guides(alpha = "none")+
  # coord_trans(x="log10", y="log10")
  scale_x_continuous(trans='log10') + scale_y_continuous(trans='log10')+
  coord_cartesian(xlim = c(1,NA), ylim=c(1,NA))

plotly::ggplotly(p1, tooltip = c("text",chosen_year_sym, "mmr_2023"))
```


## Recommendations and SDGs
### Maternal health
```{r}
#| fig-width: 7
mmr_a <- MMR |> 
  filter(!is.na(COUNTRY)) |> 
  filter(country_name!="Cook Islands") |> 
  select(ParentLocation, COUNTRY, country_name, YEAR, NumericValue) |> 
  mutate(NumericValue = round(NumericValue)) |> 
  filter(YEAR %in% c(2005, 2016, 2023)) |> 
  pivot_wider(names_from = YEAR, values_from = NumericValue, names_prefix = "mmr_") |> 
  mutate(
    mmr_05_23 = mmr_2023-mmr_2005,
    mmr_16_23 = mmr_2023-mmr_2016,
    mmr_perc_05_23 = mmr_05_23/mmr_2005*100,
    mmr_perc_16_23 = mmr_16_23/mmr_2016*100
  ) |> 
  mutate(mmr_change = case_when(mmr_05_23>=0 ~ "Worsened", 
                                mmr_05_23 <=0 ~ "Improved"))

n_sup_mh <- sdg_data |> 
  filter(cycle %in% c("Cycle 1", "Cycle 2", "Cycle 3")) |> 
  # filter(state_under_review %in% c(mmr_most$country_name)) |> 
  mutate(state_under_review = factor(state_under_review)) |> 
  filter(response_upr %in% c("Supported", "Noted/Other")) |> 
  group_by(state_under_review, response_upr) |> 
  summarise(nsup=sum(maternal_health != "Other")) |> 
  group_by(state_under_review) |> 
  mutate(perc = nsup/sum(nsup)*100,
         nsup_tot = sum(nsup)) |> 
  filter(response_upr == "Supported") |>
  left_join(state_geo, join_by(state_under_review == country)) |> 
  select(iso3, nsup, perc, nsup_tot, pop) |>
  left_join(live_births, join_by(iso3 == country_iso_3_code)) |> 
  ungroup() |> 
  mutate(nsup_stan = nsup/max(nsup)) |> 
  mutate(
    perc_cat = fct_relevel(case_when(
      perc >= 60 ~ ">=60%",
      perc < 60 ~ "<60%",
      .default = NA), ">=60%"),
    perc_cat2 = factor(case_when(
      perc > 80 ~ ">80%",
      perc >= 60 ~ "60% to 80%",
      perc < 60 ~ "<60%",
      .default = NA
    ), levels = c(">80%",
                  "60% to 80%",
                  "<60%"))
  )

mmr_b <- mmr_a |> left_join(n_sup_mh, join_by(country_name == state_under_review)) |> 
  # filter(mmr_2005>20) |>
  filter(!is.na(perc_cat))

# mmr_b |> ggplot(aes(x=perc, y=mmr_16_23))+
#   geom_point()+
#   geom_smooth()+
#   facet_wrap(.~ParentLocation)

p_a <- mmr_b |> 
  # First weight the MMR by number of livebirths for further regional analysis
  mutate(weighted_mmr_05 = mmr_2005*livebirths_2005,
         weighted_mmr_16 = mmr_2016*livebirths_2016,
         weighted_mmr_23 = mmr_2023*livebirths_2023) |> 
  group_by(ParentLocation, perc_cat) |> 
  summarise(
    weighted_rate_05 = sum(weighted_mmr_05)/sum(livebirths_2005),
    weighted_rate_16 = sum(weighted_mmr_16)/sum(livebirths_2016),
    weighted_rate_23 = sum(weighted_mmr_23)/sum(livebirths_2023)
  ) |> 
  ungroup() |> 
  mutate(weighted_diff_05_23 = weighted_rate_23-weighted_rate_05,
         weighted_diff_16_23 = weighted_rate_23-weighted_rate_16
         )

p1<-mmr_b |> group_by(ParentLocation, perc_cat) |> 
  summarise(
    n=n(), 
    mean_mmr_change = mean(mmr_05_23),
    weighted_mean_change = weighted.mean(x = mmr_05_23, w = mmr_2005));p1

p1 |> ggplot(aes(x=fct_rev(perc_cat), y = weighted_mean_change, fill = fct_rev(perc_cat)))+
  geom_col()+
  geom_text(aes(label = paste0("n=",n)), nudge_y = -6)+
  facet_wrap(.~ParentLocation)+
  labs(x="% acceptance of recommendations related to maternal health",
       y = "Average change in MMR (2016 to 2023)",
       title = "Change in MMR (2016-2023) by % acceptance of\nUPR recommendations related to maternal health",
       fill = NULL)+
  theme_bw()+
  coord_cartesian(ylim = c(min(p1$weighted_mean_change-10), 0))+
  theme(axis.text.x = element_text(angle = 15))

m1 <- glm(data = mmr_b, mmr_16_23~perc_cat)
# m2 <- lme4::lmer(mmr_05_23 ~ 1+perc_cat2+mmr_2005+(1|ParentLocation),
#                  data = mmr_b)

m3 <- glm(data = mmr_b, formula = )
summary(m1)
# summary(m2)
```
```{r}
skilled_birth %>%
  filter(SpatialDimType == "REGION") |> 
  ggplot(aes(x=year, y = NumericValue, color = region_name))+
  labs(title = unique(skilled_birth$IndicatorName))+
  geom_line()

skilled_birth_change <- skilled_birth |> 
  filter(SpatialDimType == "COUNTRY") |> 
  # filter(country_name %in% c("India", "Bhutan")) |>
  filter(!is.na(country_name)) |> 
  group_by(country_name) |> 
  mutate(start_val = NumericValue[YEAR==min(YEAR)]) |> 
  filter(start_val<90) |> 
  mutate(skilled_change = NumericValue[YEAR==max(YEAR)] - NumericValue[YEAR==min(YEAR)]) |> 
  filter(YEAR ==max(YEAR)) |> ungroup() |> 
  select(ParentLocation, country_name, NumericValue, skilled_change) |> 
  left_join(n_sup_mh, join_by(country_name==state_under_review)) |> 
  filter(!is.na(perc_cat2)) |> 
  group_by(ParentLocation, perc_cat2) |>
  summarise(
    n=n(), 
    mean_skilled_change = mean(skilled_change))


skilled_birth_change |> 
  ggplot(aes(x=perc_cat2, y = mean_skilled_change, fill = perc_cat2))+
  geom_col()+
  geom_text(aes(label = paste0("n=",n)), nudge_y = 4)+
  facet_wrap(.~ParentLocation)
```
## Tables
### Global
```{r}
table_1_global <- sdg_data |> 
  filter(!is.na(response_upr)) |> 
  group_by(cycle) |> 
  summarise(
    n = n(),
    health_related_n = sum(health_related!="Other"),
    maternal_health = sum(maternal_health!="Other"),
    abortion = sum(abortion!="Other"),
    contraception = sum(contraception!="Other")
  ) |> 
  mutate(
    health_related = paste0(health_related_n, " (", round(health_related_n/n*100), "%)"),
    maternal_health = paste0(maternal_health, " (", round(maternal_health/n*100,2), "%)"),
    abortion = paste0(abortion, " (", round(abortion/n*100, 2), "%)"),
    contraception = paste0(contraception, " (", round(contraception/n*100,2), "%)")
    ) |> 
  relocate(health_related, .after=n) |> 
  select(-health_related_n)
  

table_1_global_gt <- table_1_global |> gt() |> cols_label(
  "cycle" ~ md("UPR<br>cycle"),
  "n" ~ md("Total number of<br>recommendations"),
  "health_related" ~ "Right to health",
  "maternal_health" ~ "Maternal health",
  "abortion" ~ "Abortion",
  "contraception" ~ "Contraception"
) |> 
  tab_spanner(label = md("**Health sub-themes**<br>N (% of total recommendations)"), columns = 4:6) |> 
  gt::tab_caption(caption = "Table 1a. Number of recommendations issued in each cycle of the UPR, with further breakdown by broad association with the right to health as well as sub-themes of interest."); table_1_global_gt
```

### Global
```{r}
table_1_regional <- sdg_data |> 
  filter(!is.na(response_upr)) |> 
  group_by(wbregion, cycle) |> 
  summarise(
    n = n(),
    health_related_n = sum(health_related!="Other"),
    maternal_health = sum(maternal_health!="Other"),
    abortion = sum(abortion!="Other"),
    contraception = sum(contraception!="Other")
  ) |> 
  mutate(
    health_related = paste0(health_related_n, " (", round(health_related_n/n*100), "%)"),
    maternal_health = paste0(maternal_health, " (", round(maternal_health/n*100,2), "%)"),
    abortion = paste0(abortion, " (", round(abortion/n*100, 2), "%)"),
    contraception = paste0(contraception, " (", round(contraception/n*100,2), "%)")
    ) |> 
  relocate(health_related, .after=n) |> 
  select(-health_related_n);table_1_regional
  

table_1_regional_gt <- table_1_regional |> 
  gt(rowname_col = "cycle", groupname_col = "wbregion") |> 
  cols_label(
  "cycle" ~ md("UPR<br>cycle"),
  "n" ~ md("**Total N**"),
  "health_related" ~ md("Overall<br>Right to health"),
  "maternal_health" ~ "Maternal health",
  "abortion" ~ "Abortion",
  "contraception" ~ "Contraception"
) |>
  tab_spanner(label = md("**Health sub-themes**<br>n (% of total N)"), columns = 4:7) |> 
  tab_options(
    row_group.background.color = "grey90"
  ) |> 
   tab_style(
    style = list(
      cell_text(weight = "bold")
      ),
    locations = cells_body(
      columns = n)) |> 
  gt::tab_caption(caption = "Table 1b. Number of recommendations issued in each cycle of the UPR by region, with further breakdown by broad association with the right to health as well as sub-themes of interest."); table_1_regional_gt

gtsave(table_1_regional_gt, filename = here("output", "UPR_regional.html"))
```
